FROM almalinux:9
RUN dnf install -y nginx && \
    dnf clean all
RUN rm -rf /usr/share/nginx/html/index.html
ADD https://github.com/ManjunathaKullai1206/terraform-aws-vpc /usr/share/nginx/html/index.html
RUN chmod +r /usr/share/nginx/html/index.html

CMD ["nginx", "-g", "daemon off;"]